# Generated by Django 5.0.3 on 2024-03-28 00:39

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0004_delete_employee_employee2_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("EmployeeApp.user",),
            managers=[
                ("manager", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
